version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Projet
      MYSQL_PASSWORD: admin

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1

  php:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./app:/var/www/html
    links:
      - db
